# version: '3.8'
services:
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   restart: always
  #   ports:
  #     - "3050:80"
  #   depends_on:
  #     - backend
  #     - frontend
  mysql:
    image: mysql:8
    container_name: mysql-auth
    restart: unless-stopped
    volumes:
      - ./data/mysqldata:/var/lib/mysql
      # - ./config:/etc/mysql/conf.d # my.cnf 파일을 컨테이너에 복사
    command:
      - --bind-address=0.0.0.0 # MySQL 시작 시 bind-address를 0.0.0.0으로 설정
    ports:
      []
      # - ${MYSQL_OPEN_PORT}:3306
    env_file:
      - ./envs/env.prod
    environment:
      # - MYSQL_ROOT_HOST=mysql-auth-${NODE_ENV}
      # - MYSQL_USER=${MYSQL_USER}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
      - MYSQL_TIMEZONE=Asia/Seoul
      - TZ=Asia/Seoul
    networks:
      - network-auth

  redis:
    image: redis:alpine
    container_name: redis-auth
    restart: unless-stopped
    volumes:
      - ./data/redisdata:/data
      # - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    # env_file:
    #   - ./envs/env.prod
    networks:
      - network-auth
    # command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    ports: []
    depends_on:
      - mysql

  server:
    container_name: server-auth
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: prodution
    volumes: []
    networks:
      - network-auth
    ports:
      - 80:8000
    env_file:
      - ./envs/env.prod
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - redis
      - mysql

networks:
  network-auth:
    driver: bridge
# docker-compose --env-file .env.local up
# docker-compose --env-file .env.local up --build
